---
title: "The Relationship between Sentiment and Text Analysis, and Popularity on Twitter"
author: "Isaiah Boone"
date: "December 13, 2015"
output: pdf_document
---

#Our Topic
#Introduction
  Social Media has grown not only in the role that it plays in the life of the everyday person, but also in the role it plays in the marketing strategies and plans of large companies. We thought the idea of examining social media content and its different features would be an interesting topic to study due to its relevance and potential applications. This project should be of interest to people because it could potentially reveal underlying behavioral, possibly subconscious, patterns of people and how it relates to their responses to different social media output.  
#Why People Should Care
#Process
  We wanted to highlight different features of the text component of tweets. One of the most important text features we wanted to identify was sentiment. Sentiment Analysis is the analysis of text passages by identifying words or phrases with positive, negative, and neutral connotations within the text and using those identifiers to determine how positive, negative or neutral a given passage is. To create the sentiment score for each tweet we created a function in R that gave a score based on the number of positive, negative and neutral words and phrases. The function did this by matching words in the text with libraries of positive and negative owrds. Parts of the code and these libraries were taken from https://sites.google.com/site/miningtwitter/questions/sentiment/sentiment. We also added additional libraries in order to create a more complete library and hopefully capture terms that were left out in the AFINN dictionaries. The additional variables we included were Word Count, which counts the number of words in a given post. Passive Score, which identified if the post was more passive meaning it would say the grass was cut by John versus an active sentence which would say John cut the grass. Photo score which indicated if the post also contained a picture. Geo score which indicated if the post mentioned a country or geographic region. Personal score which informed us if the sentence was directed at the reader, meaning it contained the words "you", "you've", "your", etc. We also included an impersonal score, which indicated if the post was more about National Geographic, which we identified by words such as "we", "ours", "our", etc. The last variable we included was a time variable which indicated whether the most was made between before or after 12pm. These were the variables we used to analyze the text from tweets and we attempted to use these variables to see if it was possible to make a relatively accurate predictive model for the productivity of future tweets using these components. We measured popularity by summing the favorite count and twice the retweets. Our rationale behind doubling the weight of the retweets was that there is additional effort to retweet and we thought it should be more effective. We then split each of the tweets into 3 categories based on its popularity score. The category "Popular" was defined as tweets that were in the 25th percentile or higher in regards to popularity score. "Average" tweets were categorized as tweets that had a popularity score above the 75th percentile and below the 25th percentile. "Unpopular" tweets were marked as tweets that had a popularity score below the 75th percentile. 
  We used Random Forests in order make a learning algorithm that would predict the popularity of a tweet based on the other variables we mentioned. What we ultimately came up with was a model with an OOB of approximately 29%. Though this error rate is high, it correctly predicts the outcome of the popularity of tweets correctly more often than it does not. What this suggests is that if there are patterns to human behavior, we can use certain information provided by the model to potentially estimate the popularity a given instagram post will have.  
#What we did
We also included some very cool graphics.
#How can this be useful
#Conclusion
This can be useful because this type of analysis can potentially be applied to other companies that use and think critically about their output. Popularity score is important because it can help to spread the tweet or message a company is trying to send. Engaging its followers is extremely important to the success of various companies, especially for media companies which rely very heavily on social media outlets to reach potential customers and consumers of their product.  
